input_dir: /mnt/Datastore/usr/kptruong/astfjordbrua
output_dir: /mnt/Datastore/usr/kptruong/aastfjordbrua-output
batch_hdf5: 10  # length of each hdf5 file, in seconds (this is fixed)
dasly:
  batch: 60  # length of each batch, in seconds
  batch_gap: 30  # gap between the batch, in seconds, multiple of batch_hdf5