input_dir: /mnt/Datastore/usr/kptruong/dasly/test/test_aastfjordbrua_input
# input_dir should contain the following structure: /YYYYMMDD/dphi/HHMMSS.hdf5

database:
  database_type: postgresql
  dbapi: psycopg2
  endpoint: 129.241.154.236
  port: 5432
  database: aastfjordbrua
  table: vehicles

batch_hdf5: 10  # length of each hdf5 file, in seconds (this is fixed)

dasly:
  batch: 60  # length of each batch, in seconds
  batch_gap: 10  # gap between the batch, in seconds, multiple of batch_hdf5

lowpass_filter_freq: 0.5

decimate_t_rate: 6

gaussian_smooth:
  s1: 80
  s2: 85
  std_s: 10

binary_threshold: 2.5e-8

hough_transform:
  speed_res: 0.5
  length_meters: 600


dbscan_eps_seconds: 1  
